# -*- coding: utf-8 -*-
"""Summarizer.md

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10La7Ji3A5iF7MgH-aBd2gCYZd3z4ix5u
"""



"""**Aim**: To build a product review summarizer as well as text summarizer

**Application:** Reducing hundreds of product reviews into a summarised text consisting of maximum 10 sentences. Also an artcile can be summarized into 10-12 lines using this approach. To show the top 5 important keywords at the end of the document.

---

### **APPROACH:**<br>
Given many reviews, first all the reviews will be combined in a single text and then summarized in few lines. Articles, documents can be summarized similarly.

### Step 1: Stake Decoder Algorithm:
Collecting the text and stacking it in a queue sentence by sentence based on few conditions.

### Step 2: Calculating Similarity Score
We are calculating the similarity score based on the most frequently occuring words using different techniques of Natural Language Processing.
<br><tab>a.Stemming
  
b.Removing stop words

c.TF-IDF(Term Frequency- Inverse Document Frequency)

### Step 3: Using Stake Decoder algorithm, we can get the precise lines of summary as per our requirement.

### Step 4: Extracting five words as keywords on the basis of the importance score generated from the TF-IDF values.

The above method is employed in order to summarize to 10 lines max. We can proceed further to reduce them to 1-2 sentences. This can be done by using LSTM(Long-Short Term Memory). 
We have trained LSTM netwrok on a portion of food reviews dataset.
Due to lack of time and computational tools, we couldn't generalise LSTM results. But it gives fairly good results(sensible) as compared to using NLP methods.
"""